/** SQL 类型校验正则 */
export const READONLY_SQL_PATTERN = /^\s*(SELECT|SHOW|DESCRIBE|DESC|EXPLAIN)\b/i;
export const WRITE_SQL_PATTERN = /^\s*(INSERT|UPDATE|DELETE)\b/i;
export const DANGEROUS_SQL_PATTERN = /^\s*(DROP|TRUNCATE|ALTER|CREATE|GRANT|REVOKE)\b/i;
